### PR TITLE
src/Makefile: make install locations configurable

### PR DESCRIPTION
**Pull request by kanavin**
This allows following the distribution policies for where these
things should be placed. Defaults stay as they were.

### CODE REVIEW

**Comment by slicer69** [comment]
Looks good to me. Committing for further testing.

**Comment by Nuc1eoN** [comment]
Hi, it seems this been reverted in ae0488fa6619bd745120cb1712995a9f7712d49b? Maybe by mistake?

I'm packaging this for our distro GoboLinux and this would have been very helpful.

Thanks.

**Comment by slicer69** [comment]
Thanks for pointing this out. This was definitely not supposed to happen. I've recommitted the flexible Makefile for the 3.12 branch.

**Comment by Nuc1eoN** [comment]
Your welcome, thank you for bringing this back! This greatly eases our packaging process.

I have added a small fix in PR #28.

Please note that we still required to patch around:

https://github.com/slicer69/sysvinit/blob/40eb0cff7c4e361ecc8d0b61c204b128e4f7923f/src/Makefile#L99-L109

via `sed -i -e 's|$(ROOT)/usr|$(ROOT)|'`.

Since the ROOT of our package is `/Programs/Sysvinit/3.11` (in place of `usr/`), we need a way to unset `/usr`.

I propose to add the following changes:

```diff
 ROOT         ?=
+usrdir       ?= /usr
 base_bindir  ?= /bin
 base_sbindir ?= /sbin
-bindir       ?= /usr/bin
+bindir       ?= $(usrdir)/bin
 sysconfdir   ?= /etc
-includedir   ?= /usr/include
+includedir   ?= $(usrdir)/include
-mandir       ?= /usr/share/man
+mandir       ?= $(usrdir)/share/man
```

and
```diff
# Additional libs for GNU libc.
-ifneq ($(wildcard $(ROOT)/usr/lib*/libcrypt.*),)
+ifneq ($(wildcard $(ROOT)/$(usrdir)/lib*/libcrypt.*),)
```

This should only make it more flexible for everybody without any side-effcts or big refactors.

Would you be interested in a PR?

**Comment by slicer69** [comment]
I don't think we need a pull request to edit these four lines. I'm committing the change and adding this to the 3.12 branch.

**Comment by kanavin** [comment]
> I don't think we need a pull request to edit these four lines. I'm committing the change and adding this to the 3.12 branch.

Should it be in the main branch too?

**Comment by slicer69** [comment]
> Should it be in the main branch too?

Not until 3.12 is released.

**Pull request merged**
